# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WindowStart.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import csv
import os
import sys
from functools import partial

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QApplication, QDialog, QLabel, QLineEdit, QPushButton

from ComboBoxMethods import ComboBoxMethods
from VideoPlayer import Ui_MainWindowVideoPlayer
from WindowVideo import WindowVideo


class Ui_MainWindow(object):

    def openWIndow(self):
        self.window = QMainWindow()
        # ui = Ui_MainWindowVideoPlayer()
        self.ui = WindowVideo()
        self.ui.show()

        window.hide()
        # ui.setupUi((self.window))
        # window.hide()
        # self.window.show()

    def writeCurrentTeam(self, allfields, allboxes):

        dirTeam = os.path.dirname(__file__)
        dirTeam = dirTeam + "/Gamedata/CurrentTeam"
        f = open(dirTeam, 'r+')
        #f.write("test")

        for a, b in zip(allfields, allboxes):
            if a.text() and b.currentText():
                f.write(a.text() + "," + b.currentText() + "\n")

        # f.close()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(698, 664)
        MainWindow.setSizeIncrement(QtCore.QSize(30, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 40, 71, 21))
        self.label.setObjectName("label")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 120, 264, 51))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_2.setMaximumSize(QtCore.QSize(167772, 16777215))
        self.lineEdit_2.setMaxLength(3276)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.comboBox_2.setSizeIncrement(QtCore.QSize(1000, 0))
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout_2.addWidget(self.comboBox_2, 1, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 2, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 180, 264, 51))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_3.setMaximumSize(QtCore.QSize(167772, 16777215))
        self.lineEdit_3.setMaxLength(3276)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_3.addWidget(self.lineEdit_3, 1, 1, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.comboBox_3.setSizeIncrement(QtCore.QSize(1000, 0))
        self.comboBox_3.setObjectName("comboBox_3")
        self.gridLayout_3.addWidget(self.comboBox_3, 1, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 2, 1, 1)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 240, 264, 51))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_4.setMaximumSize(QtCore.QSize(167772, 16777215))
        self.lineEdit_4.setMaxLength(3276)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_4.addWidget(self.lineEdit_4, 1, 1, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        self.comboBox_4.setSizeIncrement(QtCore.QSize(1000, 0))
        self.comboBox_4.setObjectName("comboBox_4")
        self.gridLayout_4.addWidget(self.comboBox_4, 1, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 1, 2, 1, 1)
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(10, 300, 264, 51))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.lineEdit_5.setMaximumSize(QtCore.QSize(167772, 16777215))
        self.lineEdit_5.setMaxLength(3276)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_5.addWidget(self.lineEdit_5, 1, 1, 1, 1)
        self.comboBox_5 = QtWidgets.QComboBox(self.gridLayoutWidget_5)
        self.comboBox_5.setSizeIncrement(QtCore.QSize(1000, 0))
        self.comboBox_5.setObjectName("comboBox_5")
        self.gridLayout_5.addWidget(self.comboBox_5, 1, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 1, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 1, 2, 1, 1)
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(10, 360, 264, 51))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineEdit_6.setMaximumSize(QtCore.QSize(167772, 16777215))
        self.lineEdit_6.setMaxLength(3276)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_6.addWidget(self.lineEdit_6, 1, 1, 1, 1)
        self.comboBox_6 = QtWidgets.QComboBox(self.gridLayoutWidget_6)
        self.comboBox_6.setSizeIncrement(QtCore.QSize(1000, 0))
        self.comboBox_6.setObjectName("comboBox_6")
        self.gridLayout_6.addWidget(self.comboBox_6, 1, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 1, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_11.setObjectName("label_11")
        self.gridLayout_6.addWidget(self.label_11, 1, 2, 1, 1)
        self.gridLayoutWidget_7 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(10, 420, 264, 51))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.lineEdit_7.setMaximumSize(QtCore.QSize(167772, 16777215))
        self.lineEdit_7.setMaxLength(3276)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_7.addWidget(self.lineEdit_7, 1, 1, 1, 1)
        self.comboBox_7 = QtWidgets.QComboBox(self.gridLayoutWidget_7)
        self.comboBox_7.setSizeIncrement(QtCore.QSize(1000, 0))
        self.comboBox_7.setObjectName("comboBox_7")
        self.gridLayout_7.addWidget(self.comboBox_7, 1, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_12.setObjectName("label_12")
        self.gridLayout_7.addWidget(self.label_12, 1, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_13.setObjectName("label_13")
        self.gridLayout_7.addWidget(self.label_13, 1, 2, 1, 1)
        self.gridLayoutWidget_8 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(10, 480, 264, 51))
        self.gridLayoutWidget_8.setObjectName("gridLayoutWidget_8")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.gridLayoutWidget_8)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.gridLayoutWidget_8)
        self.lineEdit_8.setMaximumSize(QtCore.QSize(167772, 16777215))
        self.lineEdit_8.setMaxLength(3276)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_8.addWidget(self.lineEdit_8, 1, 1, 1, 1)
        self.comboBox_8 = QtWidgets.QComboBox(self.gridLayoutWidget_8)
        self.comboBox_8.setSizeIncrement(QtCore.QSize(1000, 0))
        self.comboBox_8.setObjectName("comboBox_8")
        self.gridLayout_8.addWidget(self.comboBox_8, 1, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_14.setObjectName("label_14")
        self.gridLayout_8.addWidget(self.label_14, 1, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_15.setObjectName("label_15")
        self.gridLayout_8.addWidget(self.label_15, 1, 2, 1, 1)
        self.gridLayoutWidget_9 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_9.setGeometry(QtCore.QRect(340, 120, 264, 51))
        self.gridLayoutWidget_9.setObjectName("gridLayoutWidget_9")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.gridLayoutWidget_9)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.gridLayoutWidget_9)
        self.lineEdit_9.setMaximumSize(QtCore.QSize(167772, 16777215))
        self.lineEdit_9.setMaxLength(3276)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_9.addWidget(self.lineEdit_9, 1, 1, 1, 1)
        self.comboBox_9 = QtWidgets.QComboBox(self.gridLayoutWidget_9)
        self.comboBox_9.setSizeIncrement(QtCore.QSize(1000, 0))
        self.comboBox_9.setObjectName("comboBox_9")
        self.gridLayout_9.addWidget(self.comboBox_9, 1, 3, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.label_16.setObjectName("label_16")
        self.gridLayout_9.addWidget(self.label_16, 1, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.label_17.setObjectName("label_17")
        self.gridLayout_9.addWidget(self.label_17, 1, 2, 1, 1)
        self.gridLayoutWidget_10 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_10.setGeometry(QtCore.QRect(340, 180, 264, 51))
        self.gridLayoutWidget_10.setObjectName("gridLayoutWidget_10")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.gridLayoutWidget_10)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.gridLayoutWidget_10)
        self.lineEdit_10.setMaximumSize(QtCore.QSize(167772, 16777215))
        self.lineEdit_10.setMaxLength(3276)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_10.addWidget(self.lineEdit_10, 1, 1, 1, 1)
        self.comboBox_10 = QtWidgets.QComboBox(self.gridLayoutWidget_10)
        self.comboBox_10.setSizeIncrement(QtCore.QSize(1000, 0))
        self.comboBox_10.setObjectName("comboBox_10")
        self.gridLayout_10.addWidget(self.comboBox_10, 1, 3, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        self.label_18.setObjectName("label_18")
        self.gridLayout_10.addWidget(self.label_18, 1, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        self.label_19.setObjectName("label_19")
        self.gridLayout_10.addWidget(self.label_19, 1, 2, 1, 1)
        self.gridLayoutWidget_11 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_11.setGeometry(QtCore.QRect(340, 240, 264, 51))
        self.gridLayoutWidget_11.setObjectName("gridLayoutWidget_11")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.gridLayoutWidget_11)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.gridLayoutWidget_11)
        self.lineEdit_11.setMaximumSize(QtCore.QSize(167772, 16777215))
        self.lineEdit_11.setMaxLength(3276)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_11.addWidget(self.lineEdit_11, 1, 1, 1, 1)
        self.comboBox_11 = QtWidgets.QComboBox(self.gridLayoutWidget_11)
        self.comboBox_11.setSizeIncrement(QtCore.QSize(1000, 0))
        self.comboBox_11.setObjectName("comboBox_11")
        self.gridLayout_11.addWidget(self.comboBox_11, 1, 3, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        self.label_20.setObjectName("label_20")
        self.gridLayout_11.addWidget(self.label_20, 1, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        self.label_21.setObjectName("label_21")
        self.gridLayout_11.addWidget(self.label_21, 1, 2, 1, 1)
        self.gridLayoutWidget_12 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_12.setGeometry(QtCore.QRect(340, 300, 264, 51))
        self.gridLayoutWidget_12.setObjectName("gridLayoutWidget_12")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.gridLayoutWidget_12)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.gridLayoutWidget_12)
        self.lineEdit_12.setMaximumSize(QtCore.QSize(167772, 16777215))
        self.lineEdit_12.setMaxLength(3276)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout_12.addWidget(self.lineEdit_12, 1, 1, 1, 1)
        self.comboBox_12 = QtWidgets.QComboBox(self.gridLayoutWidget_12)
        self.comboBox_12.setSizeIncrement(QtCore.QSize(1000, 0))
        self.comboBox_12.setObjectName("comboBox_12")
        self.gridLayout_12.addWidget(self.comboBox_12, 1, 3, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget_12)
        self.label_22.setObjectName("label_22")
        self.gridLayout_12.addWidget(self.label_22, 1, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget_12)
        self.label_23.setObjectName("label_23")
        self.gridLayout_12.addWidget(self.label_23, 1, 2, 1, 1)
        self.gridLayoutWidget_13 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_13.setGeometry(QtCore.QRect(340, 360, 264, 51))
        self.gridLayoutWidget_13.setObjectName("gridLayoutWidget_13")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.gridLayoutWidget_13)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.gridLayoutWidget_13)
        self.lineEdit_13.setMaximumSize(QtCore.QSize(167772, 16777215))
        self.lineEdit_13.setMaxLength(3276)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.gridLayout_13.addWidget(self.lineEdit_13, 1, 1, 1, 1)
        self.comboBox_13 = QtWidgets.QComboBox(self.gridLayoutWidget_13)
        self.comboBox_13.setSizeIncrement(QtCore.QSize(1000, 0))
        self.comboBox_13.setObjectName("comboBox_13")
        self.gridLayout_13.addWidget(self.comboBox_13, 1, 3, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.gridLayoutWidget_13)
        self.label_24.setObjectName("label_24")
        self.gridLayout_13.addWidget(self.label_24, 1, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.gridLayoutWidget_13)
        self.label_25.setObjectName("label_25")
        self.gridLayout_13.addWidget(self.label_25, 1, 2, 1, 1)
        self.gridLayoutWidget_14 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_14.setGeometry(QtCore.QRect(340, 420, 264, 51))
        self.gridLayoutWidget_14.setObjectName("gridLayoutWidget_14")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.gridLayoutWidget_14)
        self.gridLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.gridLayoutWidget_14)
        self.lineEdit_14.setMaximumSize(QtCore.QSize(167772, 16777215))
        self.lineEdit_14.setMaxLength(3276)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.gridLayout_14.addWidget(self.lineEdit_14, 1, 1, 1, 1)
        self.comboBox_14 = QtWidgets.QComboBox(self.gridLayoutWidget_14)
        self.comboBox_14.setSizeIncrement(QtCore.QSize(1000, 0))
        self.comboBox_14.setObjectName("comboBox_14")
        self.gridLayout_14.addWidget(self.comboBox_14, 1, 3, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.gridLayoutWidget_14)
        self.label_26.setObjectName("label_26")
        self.gridLayout_14.addWidget(self.label_26, 1, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.gridLayoutWidget_14)
        self.label_27.setObjectName("label_27")
        self.gridLayout_14.addWidget(self.label_27, 1, 2, 1, 1)
        self.gridLayoutWidget_15 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_15.setGeometry(QtCore.QRect(340, 480, 264, 51))
        self.gridLayoutWidget_15.setObjectName("gridLayoutWidget_15")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.gridLayoutWidget_15)
        self.gridLayout_15.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.gridLayoutWidget_15)
        self.lineEdit_15.setMaximumSize(QtCore.QSize(167772, 16777215))
        self.lineEdit_15.setMaxLength(3276)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.gridLayout_15.addWidget(self.lineEdit_15, 1, 1, 1, 1)
        self.comboBox_15 = QtWidgets.QComboBox(self.gridLayoutWidget_15)
        self.comboBox_15.setSizeIncrement(QtCore.QSize(1000, 0))
        self.comboBox_15.setObjectName("comboBox_15")
        self.gridLayout_15.addWidget(self.comboBox_15, 1, 3, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.gridLayoutWidget_15)
        self.label_28.setObjectName("label_28")
        self.gridLayout_15.addWidget(self.label_28, 1, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.gridLayoutWidget_15)
        self.label_29.setObjectName("label_29")
        self.gridLayout_15.addWidget(self.label_29, 1, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(380, 570, 121, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(540, 570, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(470, 40, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        # self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        # self.lineEdit.setGeometry(QtCore.QRect(100, 40, 141, 20))
        # self.lineEdit.setObjectName("lineEdit")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(290, 40, 141, 22))
        self.comboBox.setObjectName("comboBox")
        self.label_32 = QtWidgets.QLabel(self.centralwidget)
        self.label_32.setGeometry(QtCore.QRect(300, 10, 151, 16))
        self.label_32.setObjectName("label_32")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 698, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        allTextField = [self.lineEdit_2, self.lineEdit_3, self.lineEdit_4, self.lineEdit_5, self.lineEdit_6,
                        self.lineEdit_7, self.lineEdit_8, self.lineEdit_9, self.lineEdit_10, self.lineEdit_11,
                        self.lineEdit_12, self.lineEdit_13, self.lineEdit_14, self.lineEdit_15]
        allComboBox = [self.comboBox_2, self.comboBox_3, self.comboBox_4, self.comboBox_5, self.comboBox_6,
                       self.comboBox_7, self.comboBox_8, self.comboBox_9, self.comboBox_10, self.comboBox_11,
                       self.comboBox_12, self.comboBox_13, self.comboBox_14, self.comboBox_15]

        for box in allComboBox:
            box.addItems([" ", "Aussen", "Mitte", "Zuspiel", "Diagonal", "Libero"])
            box.currentIndexChanged.connect(partial(self.writeCurrentTeam, allTextField, allComboBox))

        cbm = ComboBoxMethods()
        cbm.filenamesToCombobox(self.comboBox)

        #self.comboBox.currentIndexChanged.connect(partial(cbm.selectionchange, self.comboBox))
        self.comboBox.currentIndexChanged.connect(partial(self.fillWidgets, allTextField, allComboBox))
        self.comboBox.currentIndexChanged.connect(partial(self.writeCurrentTeam, allTextField, allComboBox))
        self.pushButton_2.clicked.connect(self.openWIndow)
        self.pushButton.clicked.connect(partial(self.save_team, allTextField, allComboBox, self.comboBox))
        self.pushButton.clicked.connect(lambda: self.comboBox.setCurrentIndex(2))

        self.pushButton_3.clicked.connect( lambda: self.remove_file())

        self.pushButton_3.clicked.connect(lambda: self.delete_team(allTextField, allComboBox, self.comboBox))
        #self.pushButton_3.clicked.connect(lambda: self.comboBox.setCurrentIndex(self.remove_index(self.comboBox)))
        self.pushButton_3.clicked.connect(lambda: self.remove_from_cb())

        self.pushButton_3.clicked.connect(lambda: self.comboBox.setCurrentIndex(0))
        #self.pushButton_3.clicked.connect(lambda: os.remove(os.path.dirname(__file__)+"/Teams/" + self.comboBox.currentText()))

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    # combobox.setCurrentIndex(0)
    # index = combobox.findText(str(combobox.currentText()))
    # combobox.removeItem(index)
    def set_new_index(self):
        if self.comboBox.currentIndex() > 0:
            self.comboBox.setCurrentIndex(0)

    def remove_from_cb(self):
        if self.comboBox.currentIndex() > 0:
            self.comboBox.removeItem(self.comboBox.findText(str(self.comboBox.currentText())))

    def remove_file(self):
        if self.comboBox.currentIndex() > 0:
            os.remove(os.path.dirname(__file__) + "/Teams/" + self.comboBox.currentText())

    def remove_index(self, combobox):
        print(combobox.currentIndex())
        if combobox.currentIndex() == 1:
            return 2
        else:
            return 1

    def fillWidgets(self, allTextFields, allCombobox):
        dir = os.path.dirname(__file__)
        dir = dir + "/Teams/" + self.comboBox.currentText()
        result = []
        if self.comboBox.currentIndex() > 0:
            with open(dir) as csvfile:
                csv_reader_object = csv.reader(csvfile)
                for row in csv_reader_object:
                    result.append(row)
                zeilen: int = sum(1 for _ in csvfile)

                allTextFields[0].setText(result[0][0])


                for i in range(0, len(result)):

                    allTextFields[i].setText(result[i][0])

                    index = allCombobox[i].findText(result[i][1], QtCore.Qt.MatchFixedString)
                    if index >= 0:
                        allCombobox[i].setCurrentIndex(index)
        else:
            for a in allTextFields:
                a.clear()

            for b in allCombobox:
                b.setCurrentIndex(0)
    def startButtonClicked(self):
        app = QApplication(sys.argv)

        windowVideo = Ui_MainWindowVideoPlayer()
        windowVideo.setupUi(QMainWindow())
        windowVideo.show()
        sys.exit(app.exec_())

    def save_team(self, allfields, allboxes, combobox):

        dlgnewgame = QDialog()
        dlgnewgame.setFixedSize(300, 300)
        dlgnewgame.setWindowTitle("Teamname")
        team_name_label = QLabel("Spielname :", dlgnewgame)
        team_name_label.move(20, 20)

        team_name_edit = QLineEdit(dlgnewgame)
        team_name_edit.move(120, 20)
        btn_newgame = QPushButton('Neues Team erstellen', dlgnewgame)
        btn_newgame.move(20, 150)
        btn_abort = QPushButton('Abbrechen', dlgnewgame)
        btn_abort.move(150, 150)
        self.allfields = allfields
        self.allboxes = allboxes
        #self.comboBox = combobox
        print('start')
        btn_newgame.clicked.connect(partial(self.create_new_team, team_name_edit, self.allfields, self.allboxes, combobox))
        #btn_newgame.clicked.connect(lambda : self.comboBox.setCurrentIndex(6))
        btn_newgame.clicked.connect(dlgnewgame.close)
        btn_abort.clicked.connect(dlgnewgame.close)
        dlgnewgame.exec()


    def delete_team(self, allfields, allboxes, combobox):

        self.comboBox = combobox
        dirTeam = os.path.dirname(__file__)
        dirTeam = dirTeam + "/Teams/" + str(combobox.currentText())
        print(dirTeam)
        if self.comboBox.currentIndex() > 0:
            for a in allfields:
                a.clear()

            for b in allboxes:
                b.setCurrentIndex(0)

        #combobox.setCurrentIndex(0)
        #index = combobox.findText(str(combobox.currentText()))
        #combobox.removeItem(index)


        print('Ende2')

    def create_new_team(self, team_name, allfields, allboxes, combobox):

        print('StartInnen')
        print(team_name.text())
        self.comboBox = combobox
        dirTeam = os.path.dirname(__file__)
        dirTeam = dirTeam + "/Teams/" + team_name.text()
        print(dirTeam)
        f = open(dirTeam, 'w')
        for a, b in zip(allfields, allboxes):
            f.write(a.text() + "," + b.currentText() + "\n")
        print('zi')
        combobox.insertItem(2, team_name.text())


        print('Ende')

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        # self.label.setText(_translate("MainWindow", "Teamname:"))
        self.label_3.setText(_translate("MainWindow", "Spielernummer :"))
        self.label_2.setText(_translate("MainWindow", "Position: "))
        self.label_4.setText(_translate("MainWindow", "Spielernummer :"))
        self.label_5.setText(_translate("MainWindow", "Position: "))
        self.label_6.setText(_translate("MainWindow", "Spielernummer :"))
        self.label_7.setText(_translate("MainWindow", "Position: "))
        self.label_8.setText(_translate("MainWindow", "Spielernummer :"))
        self.label_9.setText(_translate("MainWindow", "Position: "))
        self.label_10.setText(_translate("MainWindow", "Spielernummer :"))
        self.label_11.setText(_translate("MainWindow", "Position: "))
        self.label_12.setText(_translate("MainWindow", "Spielernummer :"))
        self.label_13.setText(_translate("MainWindow", "Position: "))
        self.label_14.setText(_translate("MainWindow", "Spielernummer :"))
        self.label_15.setText(_translate("MainWindow", "Position: "))
        self.label_16.setText(_translate("MainWindow", "Spielernummer :"))
        self.label_17.setText(_translate("MainWindow", "Position: "))
        self.label_18.setText(_translate("MainWindow", "Spielernummer :"))
        self.label_19.setText(_translate("MainWindow", "Position: "))
        self.label_20.setText(_translate("MainWindow", "Spielernummer :"))
        self.label_21.setText(_translate("MainWindow", "Position: "))
        self.label_22.setText(_translate("MainWindow", "Spielernummer :"))
        self.label_23.setText(_translate("MainWindow", "Position: "))
        self.label_24.setText(_translate("MainWindow", "Spielernummer :"))
        self.label_25.setText(_translate("MainWindow", "Position: "))
        self.label_26.setText(_translate("MainWindow", "Spielernummer :"))
        self.label_27.setText(_translate("MainWindow", "Position: "))
        self.label_28.setText(_translate("MainWindow", "Spielernummer :"))
        self.label_29.setText(_translate("MainWindow", "Position: "))
        self.pushButton.setText(_translate("MainWindow", "Mannschaft speichern"))
        self.pushButton_2.setText(_translate("MainWindow", "Starten"))
        self.pushButton_3.setText(_translate("MainWindow", "Team löschen"))
        self.label_32.setText(_translate("MainWindow", "Mannschaft auswählen"))




if __name__ == "__main__":
    app = QApplication(sys.argv)
    window = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(window)
    window.show()
    sys.exit(app.exec_())
